#name: autoUpdateGithubIOPage # 自动更新sunsgne.github.io站点
#
#on:
#  push:
#    branches:
#      - site
#
#jobs:
#  run-coupons: # 任务名
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@main  #采用main分支下的
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v2  #安装node.js
#        with:
#          node-version: '14'
#
#
#      - name: Setup Deploy Private Key
#        env:
#          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#
#      - name: Setup Git config
#        run: |
#          git config --global user.email 583985775@qq.com
#          git config --global user.name sunsgneayo
#
#
#      - name: Deploy Hexo
#        run: |
#          npm install
#          npm install -g hexo-cli
#          hexo clean
#          hexo generate
#          hexo deploy
#
#
##          cd public/
##          git init
##          git add .
##          git commit -m 'github action'
##          git push


name: autoUpdateGithubIOPage


on:
  push:
    branches:
      - site

env:
  GIT_USER: sunsgneayo
  GIT_EMAIL: 583985775@qq.com
  THEME_REPO: sanonz/hexo-theme-concise
  THEME_BRANCH: master
  DEPLOY_REPO: sunsgneayo/sunsgneayo.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Checkout theme repo
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ env.THEME_REPO }}
#          ref: ${{ env.THEME_BRANCH }}
#          path: themes/concise

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
#          cp _config.theme.yml themes/concise/_config.yml

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm run deploy