name: autoUpdateGithubIOPage # 自动更新sunsgne.github.io站点

on:
  push:
    branches:
      - site

jobs:
  run-coupons: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的

      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '14'



      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}

        run: |
      
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Git config
        run: |
          git config --global user.email 583985775@qq.com
          git config --global user.name sunsgneayo
      - name: Deploy Hexo
        run: |
          npm install   
          npm install -g hexo-cli
          hexo clean
          hexo generate 
          hexo deploy


#          cd public/
#          git init
#          git add .
#          git commit -m 'github action'
#          git push
